name: Release

on:
  push:
    tags:
      - "*"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - run: sudo apt-get update && sudo apt-get install -y libmagickwand-dev
      - run: pipx install poetry
      - uses: actions/setup-python@v7
        with:
          cache: poetry
      - run: poetry install --with test
      - run: poetry run pytest

  publish:
    needs: test
    runs-on: ubuntu-latest
    environment: pypi
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v7
      - run: pipx install poetry
      - uses: actions/setup-python@v7
        with:
          cache: poetry
      - run: poetry build
      - uses: pypa/gh-action-pypi-publish@release/v1
